name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleaner-windows-amd64
          path: target/release/cleaner.exe

  # build-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Install Rust
  #       uses: dtolnay/rust-toolchain@stable
  #
  #     - name: Build
  #       run: cargo build --release
  #
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: cleaner-linux-amd64
  #         path: target/release/cleaner

  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #
  #     - name: Install Rust
  #       uses: dtolnay/rust-toolchain@stable
  #
  #     - name: Build
  #       run: cargo build --release
  #
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: cleaner-macos-amd64
  #         path: target/release/cleaner
